# Generated by Django 3.0.8 on 2020-07-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionacademica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
