# Generated by Django 3.0.8 on 2020-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionacademica', '0002_auto_20200726_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=30),
        ),
    ]
